### ISSUE TITLE
Requesting for help to test jar files cross platform

### ISSUE THREAD

**Issue by lchokhoe** [nus-cs2103-AY2122S2/forum#172]
Hi guys, could I get some help with testing my jar file cross platform? I just managed to fix an issue with it not opening at all but changing the build.gradle dependencies to point it to "duke.launcher" and it started working on my local device.

https://github.com/lchokhoe/ip/releases/tag/A-Release

Would really appreciate it if anyone could help me test it out (even if it isn't cross-platform). Thank you in advance!

**Comment by Punpun1643** [comment]
Works on my side using macOS 👍

**Comment by yl-ang** [comment]
Works on my side using Windows 💯

**Comment by zhongfu** [comment]
runs on linux + wayland though attempting to add or list tasks fails:

```
Caused by: java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:228)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
	at duke.DukeStorage.update(DukeStorage.java:81)
	at duke.DukeParser.updateStorage(DukeParser.java:284)
	at duke.DukeParser.todoCommand(DukeParser.java:126)
	at duke.Duke.run(Duke.java:60)
	at duke.MainWindow.handleUserInput(MainWindow.java:64)
	... 59 more
```

**Comment by lchokhoe** [comment]
Thank you all for the help with the cross-platform testing! It was immensely helpful!

I'll be closing this issue now.
