### ISSUE TITLE
Unable to run test file successfully

### ISSUE THREAD

**Issue by domlimm** [nus-cs2103-AY2122S2/forum#30]
Hello, I have been searching high and low for a solution to my problem but I can't seem to find one.

This is under `A-JUnit`, been following this [guide](https://se-education.org/guides/tutorials/junit.html).

When I do this `7b. Run the test (right-click on the class and choose Run DukeTest).`, I get the error down below.

I believe it's due to my project structure, but I'm not sure how to fix it.

Appreciate any help please! Thank you in advance!

```
Internal Error occurred.
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'duke.task.TaskTest'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:45)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	... 8 more
Caused by: org.junit.platform.commons.PreconditionViolationException: Could not load class with name: duke.task.TaskTest
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:75)
	at org.junit.platform.commons.function.Try$Failure.getOrThrow(Try.java:335)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:74)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:66)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 13 more
Caused by: java.lang.ClassNotFoundException: duke.task.TaskTest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:790)
	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
	at org.junit.platform.commons.function.Try.of(Try.java:93)
	at org.junit.platform.commons.function.Try.call(Try.java:57)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:753)
	at org.junit.platform.commons.util.ReflectionUtils.tryToLoadClass(ReflectionUtils.java:709)
	... 28 more

Process finished with exit code 254

```

Also, this is my project structure:

![image](https://user-images.githubusercontent.com/46486515/150831248-89191113-f0a9-4bcd-90fd-e0da155a4750.png)

**Comment by Spyobird** [comment]
Hi, could we have a look at your TaskTest file too. Thanks.

**Comment by domlimm** [comment]
Sorry I missed that out. Here it is:

```java
package duke.task;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class TaskTest {
    @Test
    public void dummyTest(){
        assertEquals(2, 2);
    }
}
```

I followed the instructions in this [link](https://se-education.org/guides/tutorials/junit.html) (under Intellij, without gradle) closely and repeated the steps twice but :')

**Comment by AAlghrairy** [comment]
Have you tried right-clicking the "main" folder and selecting "Mark Directory as Sources Root"?

**Comment by domlimm** [comment]
> Have you tried right-clicking the "main" folder and selecting "Mark Directory as Sources Root"? You could also try renaming the package "duke.task" under "Refactor" to not include a period.

Yes I have done that too. For the past hour, I have been trying to setup on VSCode too for JUnit but can't seem to get it working either, using this [(Extension Pack for Java (VSCode))](https://code.visualstudio.com/docs/java/extensions).

I'm re-cloning the entire repo and re-doing the JUnit setup for IntelliJ. Will check back and update in 5 minutes! Thanks!

**Comment by Spyobird** [comment]
I think you may be missing the 'main' module as a dependency for test. Perhaps look at step 8 of the guide. Hopefully that resolves the error.

**Comment by damithc** [comment]
> You could also try renaming the package "duke.task" under "Refactor" to not include a period.

The `duke.task` in the screenshot is likely a UI optimization done by Intellij, rather than an actual dot being in the package name.
![image](https://user-images.githubusercontent.com/1673303/150904937-11aa52cb-8a0a-48f5-8880-6e0e1e86def3.png)

**Comment by damithc** [comment]
@domlimm Unfortunately, setting up JUnit in Intellij has become increasingly painful over the years. If you can't get it to work after a few tries, you can try the gradle approach instead. That'll require you to learn Gradle but that's something you'll have to do soon anyway.

**Comment by domlimm** [comment]
> > You could also try renaming the package "duke.task" under "Refactor" to not include a period.
> 
> The `duke.task` in the screenshot is likely a UI optimization done by Intellij, rather than an actual dot being in the package name. ![image](https://user-images.githubusercontent.com/1673303/150904937-11aa52cb-8a0a-48f5-8880-6e0e1e86def3.png)

@damithc @AAlghrairy Hello both, I'm not so sure if renaming will help...

This is after right clicking on `duke.task` and `Refactor -> Rename`

![image](https://user-images.githubusercontent.com/46486515/150905964-6d25698b-0559-4965-9dea-ec55806ca358.png)

**Comment by domlimm** [comment]
It seems that I might have forgotten to configure the SDK for the project when loading into IntelliJ.

Followed what @Spyobird said with trying out Step 8, `File -> Project Structure -> ...`,

Realised this was empty. I remembered setting the Project's SDK when I was prompted for the first time though, there were 2 options I think I selected the wrong one :')

![image](https://user-images.githubusercontent.com/46486515/150906389-13217529-10e2-43dc-afe9-445a1590965b.png)

I'll write some tests for the `Task` portion and see if everything works out fine, and will close this thread.

Thank you so much for your help! @AAlghrairy @damithc @Spyobird 🍻

**Comment by domlimm** [comment]
Hello again, sorry last question before I close this issue...

I can't seem to fix this error in the Build Output:

![image](https://user-images.githubusercontent.com/46486515/150909122-f67ce839-29f2-4ebc-899a-9678fd933529.png)

Any idea why this might be happening? I have set `main` as the dependency `File -> Project Structure -> ...`:

![image](https://user-images.githubusercontent.com/46486515/150909208-6d5af302-2089-4a14-8395-39e44298eebb.png)

**Comment by domlimm** [comment]
Okay I've fixed all issues by running `rm -rf .idea *.iml` and then restarting IntelliJ. Everything works! Thank you all again! Closing this now!

**Comment by damithc** [comment]
Good to hear that @domlimm Good job figuring out (and sharing) some of the problems along the way.
