### ISSUE TITLE
Unable to run Duke with Gradle

### ISSUE THREAD

**Issue by 9teMare** [nus-cs2103-AY2122S2/forum#45]
When I am trying to do Week 4 iP and run Duke with **Gradle (IP - Tasks - application - run)**, the following error message shows:
```
Execution failed for task ':run'.
> Process 'command 'C:\Users\wangz\.jdks\corretto-11.0.14\bin\java.exe'' finished with non-zero exit value 1
```
It stack trace to:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':run'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\wangz\.jdks\corretto-11.0.14\bin\java.exe'' finished with non-zero exit value 1
```

My SDK is Amazon Corretto version 11.0.14, I followed the following steps when I was trying to do the increment `A-Gradle`:
- Merged the `add-gradle-support` branch to my master branch
- Followed the tutorial for scenario 2 and then scenario 1 in this given link: [SE-EDU](https://se-education.org/guides/tutorials/gradle.html)
- I could not even build my IP with Gradle initially, until I downloaded addressbook-Level-3 from [here](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle), and copied the entire `config` folder to my IP working directory
- Fixed all the checkStyle error, only then I can build my iP with Gradle

### Any help regarding how to run Duke with Gradle is greatly appreciated!

**Comment by yongxiangng** [comment]
Hello! Just to be clear I have got no clue if this works.

I've just cloned your repo and I think I managed to run your application. The issue seems to be your class name in `build.gradle` file

![image](https://user-images.githubusercontent.com/60974969/151474780-f30129e5-d597-4073-8eaa-b57eded5d858.png)

If you wish, you can clone my [repo](https://github.com/yongxiangng/ip) and try running it to see if your gradle is fine. If you can run my iP then it probably means your gradle is fine but your config files have some issues.

Reason why I said I'm not sure if this works is because I'm on linux and I'm on a different machine from last sem, but I hope it solves your problem

**Comment by limzk126** [comment]
Hi I am a senior who took CS2103T in the previous semester!

I have found the issue to your problem. The reason why you cannot run Duke with gradle is because of this block of code in build.gradle file.
```
application {
    mainClassName = "seedu.duke.Duke"
}
```
This is because seedu.duke.Duke is an invalid relative path and changing it to duke.Duke should solve the problem.

**Comment by 9teMare** [comment]
Thank you @yongxiangng @limzk126 very much! This is indeed the issue, I managed to resolve it now.
